dev.corusoft.eticketia.domain.exceptions.DomainException=error de ejecuci\u00F3n interno
# ************************* AUTH ************************* #
dev.corusoft.eticketia.domain.exceptions.auth.UserAlreadyExistsException=usuario con ID {0} ya existe
dev.corusoft.eticketia.domain.exceptions.auth.EmailAlreadyRegisteredException=el email {0} ya est\u00E1 registrado
dev.corusoft.eticketia.domain.exceptions.auth.UserNotFoundException=usuario con ID {0} no encontrado
